Test/Models/Volunteer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Test.Models
{
    public class Volunteer
    {
        public int Id { get; set; }

        [Required]
        public String FirstName { get; set; }
        [Required]
        public String LastName { get; set; }
    }
}

Test/Controllers/VolunteerController.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Test.Models;

namespace Test.Controllers
{
    public class VolunteerController : Controller
    {
        private IVolunteerRepository repository;
        private readonly AppDbContext context;

        public VolunteerController(AppDbContext context, IVolunteerRepository repo)
        {
            this.context = context;
            repository = repo;
        }

        public ViewResult Volunteers() => View(repository.Volunteers);

        public async Task<IActionResult> SearchVol(string searchString)
        {
            var volunteers = from v in context.Volunteers select v;
            if (!String.IsNullOrEmpty(searchString))
            {
                volunteers = volunteers.Where(s => s.FirstName.Contains(searchString));
            }
            return View(await volunteers.ToListAsync());
        }
    }
}

Test/Views/Volunteer/SearchVol.cshtml
@model IEnumerable<Test.Models.Volunteer>
@{ 
    ViewBag.Title = "Search for a Volunteer";
}

<form asp-controller="Volunteer" asp-action="SearchVol" method="get">
    <p>
        First Name: <input type="text" name="SearchString" />
        <input type="submit" value="Search" />
    </p>
</form>
@foreach (var item in Model)
{ 
    <table>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
            </tr>
        </tbody>
    </table>

            
            
}

Test/Views/Volunteer/Volunteers.cshtml
@model IEnumerable<Volunteer>

@{
    ViewBag.Title = "Volunteer List";

}

<h1>Volunteers</h1>

@foreach (var item in Model)
{
<table>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
        </tr>
    </tbody>
</table>
}

<a asp-action="SearchVol" asp-controller="Volunteer">Search for a Volunteer</a>