Test/Models/Opportunity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Test.Models
{
    public class Opportunity
    {
        public int Id { get; set; }

        [Required]
        public String Name { get; set; }
        [Required]
        public String Description { get; set; }
    }
}

Test/Controllers/OpportunityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Test.Models;

namespace Test.Controllers
{
    public class OpportunityController : Controller
    {
        private IOpportunityRepository repository;
        private readonly AppDbContext context;

        public OpportunityController(AppDbContext context, IOpportunityRepository repo)
        {
            this.context = context;
            repository = repo;
        }

        public ViewResult Opportunities() => View(repository.Opportunities);

        public async Task<IActionResult> SearchOpp(string searchString)
        {
            var opportunities = from v in context.Opportunities select v;
            if (!String.IsNullOrEmpty(searchString))
            {
                opportunities = opportunities.Where(s => s.Name.Contains(searchString));
            }
            return View(await opportunities.ToListAsync());
        }
    }
}

Test/Views/Opportunity/Opportunities.cshtml
@model IEnumerable<Opportunity>

@{
    ViewBag.Title = "Opportunity List";

}

<h1>Opportunities</h1>

@foreach (var item in Model)
{
    <table>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
            </tr>
        </tbody>
    </table>
}

<a asp-action="SearchOpp" asp-controller="Opportunity">Search for an Opportunity</a>

Test/Views/Opportunity/SearchOpp.cshtml
@model IEnumerable<Test.Models.Opportunity>
@{
    ViewBag.Title = "Search for a Volunteering Opportunity";
}

<form asp-controller="Opportunity" asp-action="SearchOpp" method="get">
    <p>
        Name of Opportunity: <input type="text" name="SearchString" />
        <input type="submit" value="Search" />
    </p>
</form>
@foreach (var item in Model)
{
    <table>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
            </tr>
        </tbody>
    </table>



}